
# redis
#spring:
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password:
#    lettuce:
#      pool:
#        max-active: 128
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
server:
  port: 10001